apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ngrok-data
  namespace: argocd
spec:
  generators:
    - clusters: {}
  template:
    metadata:
      name: 'ngrok-data'
      labels:
        app: ngrok-data
    spec:
      destination:
        namespace: operations 
        name: in-cluster
      project: default
      sources:
      - repoURL: 'https://nailabx.github.io/helm-charts'
        chart: ngrok-data
        targetRevision: 0.1.0
        helm:
          valueFiles:
          - $values/_values/ngrok-data.yaml
      - repoURL: 'https://github.com/nailabx/helm-charts.git'
        targetRevision: HEAD
        ref: values
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true