# ngrok Ingress Controller Configuration
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: game-2048-ingress
  namespace: {{ .Values.game.namespace }}
spec:
  ingressClassName: ngrok
  rules:
    - host: {{ .Values.ngrok.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: game-2048
                port:
                  number: 80