apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: istio-istiod
  namespace: argocd
spec:
  generators:
    - clusters: {}
  template:
    metadata:
      name: 'istio-istiod'
      labels:
        app: istio-istiod
    spec:
      destination:
        namespace: istio-system 
        name: in-cluster
      project: default
      sources:
      - repoURL: 'https://istio-release.storage.googleapis.com/charts'
        chart: istiod
        targetRevision: 1.20.2
        helm:
          valueFiles:
          - $values/_values/istio-istiod.yaml
      - repoURL: 'https://github.com/nailabx/helm-charts.git'
        targetRevision: HEAD
        ref: values
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true