apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kiali
  namespace: argocd
spec:
  generators:
    - clusters: {}
  template:
    metadata:
      name: 'kiali'
      labels:
        app: kiali
    spec:
      destination:
        namespace: istio-system 
        name: in-cluster
      project: default
      sources:
      - repoURL: 'https://kiali.org/helm-charts'
        chart: kiali-operator
        targetRevision: 1.78.0
        helm:
          valueFiles:
          - $values/_values/kiali.yaml
      - repoURL: 'https://github.com/nailabx/helm-charts.git'
        targetRevision: HEAD
        ref: values
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true